name: 🍏 iOS Builds
on:
  workflow_call:

# Global Settings
env:
  # Used for the cache key. Add version suffix to force clean build.
  GODOT_BASE_BRANCH: master
  SCONSFLAGS: verbose=yes warnings=extra werror=yes debug_symbols=no module_text_server_fb_enabled=yes

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-ios
  cancel-in-progress: true

jobs:
  ios-template:
    runs-on: "macos-latest"
    name: Template (target=template_release)
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Template (target=template_release) w/ Mono
            cache-name: ios-template-mono
            target: template_release
            tests: false
            sconsflags: module_mono_enabled=yes

          - name: Template (target=template_debug) w/ Mono
            cache-name: ios-template-mono
            target: template_debug
            tests: false
            sconsflags: module_mono_enabled=yes

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Restore Godot build cache
        uses: ./.github/actions/godot-cache-restore
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Setup Python and SCons
        uses: ./.github/actions/godot-deps

      - name: Compilation (arm64)
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} ${{ matrix.sconsflags }}
          platform: ios
          target: ${{ matrix.target }}
          tests: false

      - name: Save Godot build cache
        uses: ./.github/actions/godot-cache-save
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Copy artifacts
        run: |
          mkdir -p ~/ios-artifacts/${{ matrix.target }}
          cp -R bin/* ~/ios-artifacts/${{ matrix.target }}/

      - name: Upload individual artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ios-template-${{ matrix.target }}
          path: ~/ios-artifacts/${{ matrix.target }}
          retention-days: 1

    outputs:
      artifact-path: ios-artifacts

  upload-combined-artifact:
    needs: ios-template
    runs-on: macos-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: ios-artifacts

      - name: Upload combined artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-templates-mono-combined
          path: ios-artifacts
