name: 🍎 macOS Builds
on:
  workflow_call:

# Global Settings
env:
  # Used for the cache key. Add version suffix to force clean build.
  GODOT_BASE_BRANCH: master
  SCONSFLAGS: verbose=yes warnings=extra werror=yes module_text_server_fb_enabled=yes

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-macos
  cancel-in-progress: true

jobs:
  build-macos:
    runs-on: "macos-latest"
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          #- name: Editor (target=editor, tests=yes)
          #  cache-name: macos-editor
          #  target: editor
          #  tests: true
          #  bin: "./bin/godot.macos.editor.universal"

          - name: Editor w/ Mono (target=editor)
            cache-name: macos-editor-mono
            target: editor
            build-mono: true
            sconsflags: module_mono_enabled=yes
            tests: false
            bin: "./bin/godot.macos.editor.universal.mono"

          #- name: Template (target=template_release)
          #  cache-name: macos-template
          #  target: template_release
          #  tests: true
          #  sconsflags: debug_symbols=no tests=yes
          #  bin: "./bin/godot.macos.template_release.universal"

          #- name: Template w/ Mono (target=template_release)
          #  cache-name: macos-template-mono
          #  target: template_release
          #  build-mono: true
          #  tests: true
          #  sconsflags: module_mono_enabled=yes tests=yes
          #  bin: "./bin/godot.macos.template_release.universal.mono"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Restore Godot build cache
        uses: ./.github/actions/godot-cache-restore
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Setup Python and SCons
        uses: ./.github/actions/godot-deps

      - name: Setup Vulkan SDK
        run: |
          sh misc/scripts/install_vulkan_sdk_macos.sh

      - name: Compilation (x86_64)
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} ${{ matrix.sconsflags }} arch=x86_64
          platform: macos
          target: ${{ matrix.target }}
          tests: ${{ matrix.tests }}

      - name: Compilation (arm64)
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} ${{ matrix.sconsflags }} arch=arm64
          platform: macos
          target: ${{ matrix.target }}
          tests: ${{ matrix.tests }}

      - name: Save Godot build cache
        uses: ./.github/actions/godot-cache-save
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Prepare artifact
        run: |
          lipo -create ./bin/godot.macos.${{ matrix.target }}.x86_64.mono ./bin/godot.macos.${{ matrix.target }}.arm64.mono -output ${{ matrix.bin }}
          rm ./bin/godot.macos.${{ matrix.target }}.x86_64.mono ./bin/godot.macos.${{ matrix.target }}.arm64.mono
          strip bin/godot.*
          chmod +x bin/godot.*
          cp -r misc/dist/macos_tools.app ./bin/Godot.app
          mkdir -p ./bin/Godot.app/Contents/MacOS
          mv ${{ matrix.bin }} ./bin/Godot.app/Contents/MacOS/Godot
          chmod +x ./bin/Godot.app/Contents/MacOS/Godot
          codesign --force --timestamp --options=runtime --entitlements misc/dist/macos/editor.entitlements -s - ./bin/Godot.app


      - name: Generate C# glue
        if: ${{ matrix.build-mono }}
        run: |
          ./bin/Godot.app/Contents/MacOS/Godot --headless --generate-mono-glue ./modules/mono/glue

      - name: Build .NET solutions
        if: ${{ matrix.build-mono }}
        run: |
          ./modules/mono/build_scripts/build_assemblies.py --godot-output-dir=./bin

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: ${{ matrix.cache-name }}

      - name: Unit tests
        if: ${{ matrix.tests }}
        run: |
          ./bin/Godot.app/Contents/MacOS/Godot --version
          ./bin/Godot.app/Contents/MacOS/Godot --help
          ./bin/Godot.app/Contents/MacOS/Godot --test --force-colors
